name: Python application

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      working-directory: ./DCM_group9
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      working-directory: ./DCM_group9
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Grant execute permission to the script
      working-directory: ./DCM_group9/scripts
      run: |
        chmod +x run_tests.sh
    - name: Test with pytest
      working-directory: .
      run: |
        ./DCM_group9/scripts/run_tests.sh # pytest

  format:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run format.yml workflow
        run: |
          # Trigger the format.yml workflow using the workflow_dispatch event
          curl -X POST -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" -H "Accept: application/vnd.github.everest-preview+json" https://api.github.com/repos/${{ github.repository }}/actions/workflows/format.yml/dispatches -d '{"ref":"main"}'
